name: Build

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: default
    steps:
    - name: Checks out repository
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{vars.DOCKER_USER}}
        password: ${{secrets.DOCKER_PAT}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup build environment
      id: setup
      run: |
        cp build-resources/nginx-default.conf .
        echo "dockertag=pontusc/aboutme:$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        cache-from: type=registry,ref=/aboutme${{vars.DOCKER_USER}}:latest
        tags: ${{steps.setup.outputs.dockertag}}
      env:
        DOCKER_USER: ${{vars.DOCKER_USER}}
