name: Nginx image build

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        echo "$DOCKER_PAT" | docker login -u $DOCKER_USER --password-stdin
        cp build-resources/nginx-default.conf .
        docker build . --file Dockerfile --tag aboutme:$(date +%s)
      env:
        DOCKER_PAT: ${{ secrets.DOCKER_PAT }}
        DOCKER_USER: ${{ vars.DOCKER_USER }}
