name: Build & Deploy

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_TAG: ${{ steps.setup.outputs.dockertag}}
    environment: default
    steps:
    - name: Checks out repository
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{vars.DOCKER_USER}}
        password: ${{secrets.DOCKER_PAT}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup build environment
      id: setup
      run: |
        echo "dockertag=pontusc/aboutme:$(date +%s)" >> $GITHUB_OUTPUT

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        cache-from: type=registry,ref=${{vars.DOCKER_USER}}/aboutme:latest
        cache-to: type=inline
        tags: ${{steps.setup.outputs.dockertag}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: default
    env:
      DOCKER_TAG: ${{needs.build.outputs.DOCKER_TAG}}
    steps:
    - name: Checkout homelab repo
      uses: actions/checkout@v4
      with:
        repository: pontusc/homelab
        token: ${{secrets.GITHUB_TOKEN}}
        path: homelab

    - name: Update k8s manifest
      run: |
        ls
        cd homelab/apps/aboutme
        sed -i "s|pontusc/aboutme:.*|pontusc/aboutme:$DOCKER_TAG|" aboutme.yml
        cat aboutme.yml

    - name: Commit and push change
      run: |
        cd homelab
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git commit -a -m "Update aboutme manifest to latest image tag" || exit 0
        git push
