name: Nginx image build

"on":
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checks out repository
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ vars.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PAT }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup build environment
      run: |
        cp build-resources/nginx-default.conf .

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: pontusc/aboutme:$(date +%s)
