name: Build & Deploy
"on":
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      DOCKER_TAG: ${{ steps.setup.outputs.dockertag}}
    environment: default
    steps:
      - name: Checks out repository
        uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3.4.0
        with:
          username: ${{vars.DOCKER_USER}}
          password: ${{secrets.DOCKER_PAT}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Setup build environment
        id: setup
        run: |
          echo "dockertag=pontusc/aboutme:$(date +%s)" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=registry,ref=${{vars.DOCKER_USER}}/aboutme:latest
          cache-to: type=inline
          tags: ${{steps.setup.outputs.dockertag}}
          build-args: |
            APP_VERSION=1.0.${{github.run_number}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: default
    env:
      DOCKER_TAG: ${{needs.build.outputs.DOCKER_TAG}}
    steps:
      - name: Checkout deployments repository
        uses: actions/checkout@v4
        with:
          repository: pontusc/deployments
          token: ${{secrets.PAT_TOKEN}}

      - name: Update manifest
        run: |
          cd aboutme
          sed -i "s|pontusc/aboutme:.*$|$DOCKER_TAG|" aboutme.yml

      - name: Commit
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -a -m "BOT: ${{github.event.head_commit.message}}"

      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{secrets.PAT_TOKEN}}
          repository: pontusc/deployments
